jef/streetmerchant

package-lock.json, package.json
=> feat: add conventional commits

README.md
Updated the README.md file to include all the possible store names to be used in the `.env' file
=> docs: add debian support and store info

README.md
adding EVGA to table checklist
=> docs: add `EVGA` to table checklist

src/store/nvidia.ts
Fixes #2 
This should reduce load on Nvidia servers, and (hopefully) be faster for y'all.
Endpoints tested on my own Ruby script. I can't currently run chromium in my test environment so I'm providing the change for y'all without having tested it within `nvidia-snatcher`.
=> feat: update to check if FE in-stock via Digital River

README.md, src/index.ts, src/store/amazon.ts, src/store/index.ts
=> feat: add Amazon links

README.md
Need to add Amazon to supported store names missed in #26
=> docs: add `amazon`

.env.example, package-lock.json, package.json, src/config.ts, src/notification/index.ts, src/notification/slack.ts
Integrates slack and introduces notification method configuration.
"@slack/web-api": "^5.12.0"
=> feat: slack integration

README.md, src/config.ts, src/index.ts
Puts Navigation Timeout in a variable in config.
=> feat: page timeout

.env.example, README.md, src/config.ts, src/index.ts, src/notification/index.ts, src/notification/slack.ts
- Adds doc for Slack
- Change the way notification test happens and cycles through all notifications for testing
- Lexicographical ordering of some doc
- Reorganize configuration variables
- Remove verbose configuration
=> refactor: doc and notification

src/config.ts
Adding Mint Mobile carrier for SMS notifications.
=> feat(notification): add mint mobile carrier

src/store/model/amazon-ca.ts, src/store/model/amazon.ts, src/store/model/bandh.ts, src/store/model/bestbuy.ts, src/store/model/evga.ts, src/store/model/microcenter.ts, src/store/model/newegg.ts
Normalized model names including those in #93, because each contributer wrote the model in their own style.
=> chore(store): normalize model names

src/config.ts, src/notification/notification.ts
Closes #91 
Fixes sounds not playing.
=> fix(notification): wrong condition for sounds playing

README.md, src/store/model/asus.ts, src/store/model/index.ts
Adds the Asus company store for TUF models
NA
None
=> feat(store): add asus

README.md
=> docs: add pushover api generation link

src/index.ts, src/store/lookup.ts
- Extract lookup process from #110
- Add `await` back to function calls that are `async`
=> refactor: extract lookup

README.md, src/store/lookup.ts, src/store/model/adorama.ts, src/store/model/amazon-ca.ts, src/store/model/amazon.ts, src/store/model/asus.ts, src/store/model/bandh.ts, src/store/model/bestbuy.ts, src/store/model/evga.ts, src/store/model/microcenter.ts, src/store/model/newegg.ts, src/store/model/nvidia.ts, src/store/model/store.ts
- Filters third party vendors from Amazon and getting outrageous pricing
- Change Store objects properties for ordering
=> chore(store): filter amazon third party vendors

src/store/model/nvidia.ts
Addresses the below false positive:
=> fix(nvidia): false positives

README.md
Fix typo.  PUSHOVER_USERNAME should be PUSHOVER_USER
Fixes #128 
Just verify other code uses USER instead of USERNAME
That code is here: https://github.com/jef/nvidia-snatcher/blob/main/src/config.ts#L40
=> docs: update pushover variables

README.md, package-lock.json, package.json, src/config.ts, src/notification/desktop.ts, src/notification/notification.ts
Uses [node-notifier](https://www.npmjs.com/package/node-notifier) to provide cross-platform desktop notifications. Useful when sound is muted and potentially faster than other means of notification.
Tested with `npm run test:notification`. 
`node-notifier`
=> feat(notification): add desktop notifications

src/store/model/adorama.ts, src/store/model/amazon.ts
Added new listing for PNY xlr8 rbg on Amazon and Adorama
=> chore(store): pny listings

README.md, src/store/model/index.ts, src/store/model/newegg-ca.ts
Adds newegg.ca to supported stores
Discord is xdMatthewbx#1337
Tested running with `newegg-ca` added to stores list and am not encountering errors. Additionally stock alerts appear to be functioning but that may not be the case as none have actually come in stock yet.
=> feat(store): add newegg.ca

src/store/model/officedepot.ts
Filter out their error page to avoid false positive.
=> chore(store): officedepot oos label

src/store/model/evga.ts
- Add error text for EVGA website
I want to add another key, but will refactor later.
=> chore(store): add errors for evga

src/store/model/index.ts, src/store/model/zotac.ts
=> feat(store): add zotac store

src/store/model/evga.ts
Added lower tier gaming model of FTW3 and updated descriptions.
=> feat(store): add evga model

src/store/model/bandh.ts
B&H removed the Tuff, so commented it out for now
=> fix(store): bandh removed cards

src/store/model/amazon.ts
Amazon added the strix, so we should watch it.
=> chore(store): strix on amazon

package.json, src/__test__/notification-test.ts, src/config.ts, src/index.ts, src/logger.ts, src/notification/desktop.ts, src/notification/discord.ts, src/notification/email.ts, src/notification/notification.ts, src/notification/pushbullet.ts, src/notification/pushover.ts, src/notification/slack.ts, src/notification/sms.ts, src/notification/sound.ts, src/notification/telegram.ts, src/notification/twitter.ts, src/store/lookup.ts, src/store/model/bestbuy-ca.ts, src/store/model/helpers/nvidia.ts, src/store/model/index.ts, src/store/model/store.ts
Closes #241 
- Reduces some code and inconsistencies between logs
- Add log to inform user that they need to login
- Fixes opening browser by default
- Updates notifications to use the `Print` constant now
- Converts `interface`s that should really be `type`s
=> chore(misc): normalize logs

src/notification/sms.ts
Noticed that some people in the discord were trying to use the SMS notifications without setting up email as well; quick check just to make sure the user knows.
=> chore(notification): warn user of improper sms and email config

README.md, src/config.ts, src/notification/discord.ts, src/store/lookup.ts
- Adds ability to have multiple Discord roles and webhooks
- Quality of life change for environment variables
=> feat: multiple discord roles and webhooks, qol for envs

src/store/model/bestbuy.ts, src/store/model/newegg.ts
=> feat(stores): add 3090 for bestbuy, newegg

src/config.ts
bell,fido,rogers,kudo, and virgin mobile
Adds additional Canadian phone carriers for SMS service
I am Canadian
Tested locally for bell and is working using npm run test:notification
=> chore(notification): additional ca carriers

src/notification/twilio.ts
=> fix(notifications): twilio client creation

src/store/model/nvidia.ts
=> fix(store): container names on `nvidia`

README.md
We've been getting a lot of questions about supported brands and models so I added them to the readme.
=> docs: add brands and models

src/store/model/amazon-de.ts, src/store/model/amazon-nl.ts
=> fix: `amazon.{nl,de}` test urls

README.md
Small change to add a text link to discord. Found it wasnt that visible with the CI image next to it.
=> chore: Add discord url to top menu

README.md
Simple addition to readme to reflect ATT Prepaid support.
=> docs: add at&t prepaid support

src/store/model/microcenter.ts
Fixes #439 
Adds the FTW3 Ultra Microcenter
=> feat(store): add ftw3 ultra to microcenter

README.md, src/store/model/alternate.ts, src/store/model/index.ts, src/store/model/mediamarkt.ts, src/store/model/notebooksbilliger.ts, src/store/model/store.ts
Fixes #195
Added Notebooksbilliger, Alternate and Mediamarkt
Basic tests with test card and live cards.
=> feat: add german stores

src/store/model/amazon-de.ts
=> feat: add rog strix oc to amazon-de

src/config.ts, src/index.ts, src/notification/pushover.ts, src/notification/sound.ts, src/types/play-sound.d.ts, src/types/puppeteer-extra-plugin-block-resources.d.ts, src/types/pushbullet.d.ts, src/types/pushover-notifications.d.ts
I've gone through the `README` of imported modules without an `@types/package` definition and added the basic API usage.
=> chore: add typescript definitions for custom types

src/store/lookup.ts
Applying patch from https://gist.github.com/resinbeard/bb4f597f53fa537f359c2a45a13d3453
Fixes #417 
Has been running for a day inside a docker and this resolved the issue #417 just fine.
=> feat: clear cookies and cache

src/store/model/mediamarkt.ts
Description
updated Mediamarkt with Nvidia 3090 cards
N/A
=> chore: more links for `mediamarket`

README.md, src/store/model/caseking.ts, src/store/model/index.ts, src/store/model/proshop-de.ts
Added German Caseking and Proshop Store with 3080 and 3090 models
=> feat: add caseking and proshop-de store

README.md, src/store/model/azerty.ts, src/store/model/index.ts
Add support for azerty.nl
Running it myself
=> feat(store): support for azerty

src/store/model/pccomponentes.ts
Fixes #560 
Fixed bug for PCComponentes shop not matching the established labels.
=> fix(store): pccomponents model normalization

src/store/model/asus.ts
Oddly enough fixes the asus 503 error
=> fix: asus store links

src/store/model/index.ts
Page sleep was broken after PR #576 duo to a typo, sorry.
=> fix: page sleep

src/config.ts, src/store/model/index.ts, web/index.html
Fixes #601
And also adds back the logs
=> fix: update new additions with web panel and sleep operations

web/index.html
=> chore(web): prettify

README.md
add origin country to non-US stores in the readme.
=> docs: add origin country to non-US stores

README.md, src/store/model/bestbuy.ts
=> chore(store): add 3070 to best buy

src/store/model/evga.ts
=> chore(evga): add 3070 cards

src/store/model/bestbuy.ts
=> chore(bestbuy): add 3070 models

src/notification/pushbullet.ts, src/types/pushbullet.d.ts
=> fix: update pushbullet import to match package

Dockerfile
Added version .txt to docker image.
=> fix(banner): add version to docker image

src/store/model/newegg-ca.ts
=> chore(newegg-ca): add evga ftw3 3080 and gigabyte vision oc 3080

src/store/model/asus.ts
Adding the 3090 TUF OC, PR includes inventory check.
1) Navigate to Asus page to confirm URL hasn't changed or product has disappeared
None
=> chore(asus): add 3090 tuf oc

src/store/model/proshop-de.ts
Adding the 3070 cards from Proshop Germany (prohsop-de)
Navigate to Proshop.de page to confirm URL hasn't changed or product has disappeared
=> chore(proshop-de): add 3070 cards

src/store/model/newegg-ca.ts
Added real time inventory lookup for Newegg Canada cards
Based on #664 
Also added 5 new cards
Runs without issue when card is out of stock
Same api as newegg.com
=> feat(newegg-ca): realtime api

src/store/model/index.ts
This should always have all possible combinations. And also set min/max page sleep to sane defaults.
=> fix(filterBrandsSeriesModels): always loop all stores

src/store/model/amazon-ca.ts, src/store/model/newegg-ca.ts, src/store/model/newegg.ts
Changes:
- Added amazon.ca
- Added newegg.ca
- Noticed an incorrect item ID on newegg.com so fixed that too
Motivation: To get myself a 5950x! Let's go!!
Double-checked URLs, double-checked product numbers, and started running it. Seems to run fine.
=> feat(store): add zen 3 to more stores

CODE_OF_CONDUCT.md, README.md, src/store/model/index.ts, src/store/model/memoryexpress.ts
Adding MemoryExpress website in Canada. Only track the online store
stock for now. Might add the stores stock later like microcenter.
Only track Ryzen 5000-series for now because RTX 3000-series is only
available in store backorder.
- Tested with In Stock product using test:series
=> feat: memoryexpress website support

src/store/model/amazon-ca.ts
=> feat(amazon-ca): add ps5

README.md, src/store/model/arlt.ts, src/store/model/galaxus.ts, src/store/model/index.ts
I fixed a typo in the Arlt store (5950x was labelled as 5900x) and I added the Galaxus (DE) store with the zen 3 links.
I tested items that are in stock and items that are not in stock, as well as price recognition for 3-digit and 4-digit amounts.
=> feat(galaxus): add zen 3

README.md, src/config.ts, src/store/model/amazon.ts, src/store/model/bestbuy.ts, src/store/model/gamestop.ts, src/store/model/newegg.ts, src/store/model/store.ts, src/store/model/target.ts, src/store/model/walmart.ts
Closes #506
Adding Xbox Series X and S to the scanner
I am trying to purchase an Xbox on release day :)
Ran npm start run locally and scanner passed back expected results.
went through lint
npm start run
modified models in .env file to search for xboxsx and xboxss
=> feat(store): add xbox series x and s

README.md
Updating the README file to include possible strings for AMD Ryzen CPUs
=> docs: add `amd` models

Dockerfile
Fixes #744 
Modified Dockerfile to include the web directory
1) Add web directory to Dockerfile
2) Successfully build container
3) Launch container and attempt to browse to webserver
None
=> fix(docker): copy web directory

src/store/model/target.ts
Add `Ship it` button selector to Target store
=> feat(target): add additional selector for 'ship it'

README.md
Added FAQ to why Amazon Pages open up to errors
=> docs: add amazon error to faq

src/store/model/coolmod.ts
Add Zen 3 Ryzen to Coolmod Store
=> feat(coolmod): add zen 3

README.md
=> docs: small typo on canadacomputers

src/store/model/bestbuy-ca.ts
=> fix(bestbuy-ca): use proper selector

src/store/model/amazon.ts
=> fix(amazon): add 5800x and 5600x

src/store/model/aria.ts, src/store/model/ccl.ts, src/store/model/currys.ts, src/store/model/ebuyer.ts, src/store/model/novatech.ts, src/store/model/overclockers.ts, src/store/model/scan.ts
Add Ryzen CPU links to UK stores.
Fixes #821 
Auto tests run on commit, lint etc. run locally with new store links, getting many out of stock responses as expected.
=> chore: add amd cpus to uk stores

src/logger.ts, src/notification/email.ts, src/notification/telegram.ts
Sometimes add to cart link does not work, so I'm sending also the product link.
=> feat(notification): add product link to email and telegram

src/store/model/canadacomputers.ts
Canadacomputers not having Ryzen 5000 series links
Tested Working on my PC
Added Ryzen 5000 Series Links
=> feat(canadacomputers): add ryzen 5000 series

src/store/model/amazon.ts, src/store/model/bandh.ts, src/store/model/bestbuy.ts, src/store/model/newegg.ts
Added more 3070 links. Also reorganized them a bit so the series grouped together rather than scattered.
Ran this version of the code on my machine and was able to purchase a card! Thank you so much for sharing this code with others!
None
=> chore: add more 3070 cards, reorder links

src/store/model/coolmod.ts
Fixes #835
The maxPrice was not added to the original .ts
I have tested in a real enviroment, as there was one 3080 that was causing the bug in the coolmod store.
=> feat(coolmod): add `maxPrice`

README.md
Remove duplicated models from the list and clean up formatting
=> docs: remove duplicated models

package-lock.json, package.json, src/index.ts, src/notification/discord.ts, src/notification/mqtt.ts, src/notification/philips-hue.ts, src/notification/slack.ts, src/notification/telegram.ts, src/notification/twilio.ts, src/notification/twitch.ts, src/store/includes-labels.ts, src/store/lookup.ts, src/store/model/helpers/card.ts, src/store/model/helpers/nvidia-cart.ts, src/types/play-sound.d.ts, src/types/pushbullet.d.ts, src/util.ts, src/web/index.ts
Additional linting fixes that align with new xojs update.
=> chore: update dependencies

src/store/model/newegg.ts
=> chore(newegg): add Corsair SF PSUs

src/store/model/walmart.ts
Note: Walmart doesn't currently have listings for the other Zen 3 processers at this time.
=> chore(walmart): add 5900x

README.md, src/store/model/amd-it.ts, src/store/model/index.ts
Added the italian amd store and the amd radeon rx 6800 xt to the listing.
=> chore(store): add amd-it store and RX 6800 XT

src/store/model/overclockers.ts
improvement(store): add 6800 & 6800xt cards to overclockers
=> chore(store): add 6800 & 6800xt cards to overclockers

src/store/model/ebuyer.ts
improvement(store): add 6800 & 6800xt cards to ebuyer
=> chore(store): add 6800 & 6800xt cards to ebuyer

src/store/model/scan.ts
improvement(store): add amd reference 6800 & 6800xt cards to scan
=> chore(store): add 6800 & 6800xt cards to scan

src/store/model/currys.ts
=> chore(store): add 3070 series currys

src/store/model/ccl.ts
=> chore(store): Added RX6800 series to ccl store

src/store/model/microcenter.ts
Added Asus Strix OC 3080 to microcenter.
=> chore(microcenter): add Strix OC

README.md
Update the supported store in the README.
=> docs: update supported stores

src/store/model/amazon-it.ts, src/store/model/comet.ts, src/store/model/euronics.ts, src/store/model/unieuro.ts
This PR adds new links for the Italian stores (i.e., amazon-it, unieuro, euronics, and comet). In particular, it adds almost all the GPU and CPU on amazon-it, and the Microsoft console on the other stores.
I check the validity of each link.
=> feat(store): update the italian store links

src/store/model/bestbuy-ca.ts
-  Fixes #962 
- Added PS5 Disk and Digital Edition into bestbuy-ca store.
=> chore(bestbuy-ca): add ps5 console

README.md, src/store/model/index.ts, src/store/model/wipoid.ts
=> feat(store): add wipoid store

src/store/model/alternate.ts
added rx6800tx AIB links to the alternate store
=> chore(alternate): add rx6800xt

src/store/model/caseking.ts
this adds AIB model links to caseking
=> chore(caseking): add rx6800xt

src/store/model/microcenter.ts
=> chore(microcenter): add 3070 models

src/store/model/amd-de.ts
=> chore(amd-de): add rx6800xt

README.md, src/store/model/gamestop-de.ts, src/store/model/index.ts
Add support for Gamestop DE. Allow checking of PS5 disc and digital version availability.
=> feat(store): add Gamestop DE

README.md, src/store/model/euronics-de.ts, src/store/model/index.ts
Add Euronics Germany store support. Checks for XBox Series S
=> feat(store): add Euronics DE

README.md, src/store/model/antonline.ts, src/store/model/index.ts
=> feat(store): add antonline store

src/store/model/cyberport.ts
During update process wrong urls have been pasted into cyberport. Removed them as I currently know of no active urls.
=> chore(cyberport): remove xbox/ps5

README.md, src/store/model/expert.ts, src/store/model/index.ts
Add support for expert. Allow checking of PS5 disc and digital version availability, as well as XBox Series S.
=> feat(store): add expert

src/store/model/saturn.ts
=> chore(saturn): add 3060ti

src/store/model/mediamarkt.ts
=> chore(mediamarkt): add 3060ti

src/store/model/bandh.ts
[bandh] Add 3060 TI
Fixes #1090
=> chore(bandh): add 3060ti

src/store/model/alternate.ts, src/store/model/amazon-de.ts, src/store/model/amazon-es.ts, src/store/model/amazon-fr.ts, src/store/model/amazon-it.ts, src/store/model/amazon-uk.ts, src/store/model/euronics-de.ts, src/store/model/mediamarkt.ts, src/store/model/saturn.ts
Fix euroFormat for several EU stores.
Add Xbox Series X, PS5 disc/digital to Euronics (DE).
Add PS5 disc bundle to Alternate.
Change test item on several EU Amazon sites to a product available.
=> chore(store): update eu stores

src/store/model/expert.ts, src/store/model/otto.ts
Messed up with the euroFormat value for Expert and Otto which have already been pulled. This fixes the issue.
=> fix(store): update euroFormat for expert and otto

README.md, src/store/model/index.ts, src/store/model/medimax.ts
Add support for Medimax. Allow checking of PS5 disc and digital version availability.
=> feat(store): add Medimax

README.md, src/store/model/index.ts, src/store/model/spielegrotte.ts
Add support for Spielegrotte. Allow checking of PS5 disc and digital version availability.
=> feat(store): add spielegrotte

README.md, src/store/model/amazon-de-warehouse.ts, src/store/model/index.ts
Add support for amazon (de) warehouse. Allow checking of PS5 disc and digital version availability, as well as XBox Series X and S.
=> feat(store): add amazon-de-warehouse

src/store/model/expert.ts, src/store/model/mediamarkt.ts, src/store/model/saturn.ts
Add backoffStatusCodes to Expert, Mediamarkt and Saturn.
Change captcha container for Mediamarkt and Saturn as it wasn't recognized before. Maybe this is solving this.
=> fix(store): add backoffStatusCodes and new captcha container

src/store/model/zotac.ts
Added 3080 amp holo to zotac.ts
Closes #907 
`npm run start`  /s
=> chore(zotac): add 3080 amp holo

src/store/model/newegg.ts
=> chore(newegg): add 3060ti models

README.md
added step for navigating to the folder, for newbies
=> docs: add cd step

src/store/model/aria.ts, src/store/model/box.ts, src/store/model/currys.ts, src/store/model/ebuyer.ts, src/store/model/novatech.ts, src/store/model/overclockers.ts, src/store/model/scan.ts, src/store/model/very.ts
Added a few new pages to existing sites for RTX 3060 TI
=> chore(store): add 3060ti to link builders

src/store/model/memoryexpress.ts
Added the 6800xt and 3080 to the Memory Express store.
Currently running the scraper with these added.
None.
=> chore(memex): add 3080 and 6800xt

src/store/model/scan.ts
Fixes #919 
Ran changes locally and no longer get erroneous notification.
=> fix(scan): links builder

.github/workflows/stale.yaml, package.json
- Add stale cron job
- Remove warning for `fixme` comments
=> ci: add stale cron job

src/store/lookup.ts, src/store/model/amazon-de.ts, src/store/model/otto.ts, src/store/model/store.ts
Fixes #1132
Fixes #1163
Adds the ability to use labels for links in special use cases
=> feat(store): add custom labels for links

docs/reference/filter.md, src/store/model/index.ts, src/store/model/walmart-ca.ts
=> feat(store): add Walmart (CA)

docs/reference/filter.md, src/store/model/index.ts, src/store/model/toysrus.ts
=> feat(store): add Toys R Us

src/store/model/amd.ts, src/store/model/bestbuy.ts, src/store/model/microcenter.ts, src/store/model/newegg.ts
Added direct urls for rx 6900 xt gpu for following model classes
microcenter
newegg
bestbuy
amd official store
=> chore(store): add rx6900xt for microcenter, newegg, bestbuy, amd

src/store/model/officedepot.ts
feat: add 3070 card to office depot
=> chore(officedepot): add 3070

src/store/model/amazon-ca.ts
added some 3070 cards on amazon-ca
I built it and it worked. Then I used it and it worked.
I also tested all the links manually
=> chore(amazon-ca): add rtx 3070 cards

src/store/model/alternate.ts, src/store/model/amd-de.ts, src/store/model/mindfactory.ts
RX 6800 and 6900xt  for amd-de and bits for mindfactory and alternate
=> chore(store): add a few AMD listings for German stores

src/store/lookup.ts
Reduces `request interception not enabled` error spam.
=> fix(adblock): proxy another function to produce less errors

docs/reference/filter.md
- Add missing AMD-UK store to docs
=> docs(store): add missing uk store

src/web/index.ts
=> fix(webui): handling of file serving

src/store/model/alternate.ts, src/store/model/mindfactory.ts
add some Radeon models for German stores
=> chore(store): add some radeon models for German stores

package-lock.json, package.json
Fixes https://github.com/jef/streetmerchant/issues/1437
=> fix(proxy): update proxy module

src/store/model/amazon.ts
Added missing cards I've found on amazon to the list:
Zotac 3080 trinity oc
EVGA 3090 FTW3 ultra
Sapphire 6900xt
XFX 6900xt
=> chore(amazon): add nvidia and amd cards

src/store/model/galaxus.ts
Description
price checking was broken
Testing
tested with different pricing
=> fix(galaxus): maxPrice selector

src/store/model/newegg.ts
=> chore(newegg): add links for rx6800xt and rx6800

docs/reference/filter.md, src/store/model/bestbuy.ts
removed duplicate cards and added new evga and pny cards
=> chore(bestbuy): add 3060ti cards

src/store/model/proshop-de.ts
fixes out of stock condition for proshop-de
=> feat(proshop-de): add proshop-de inStock selector

docs/help/general.md
Fixing this to prevent any possible mistakes from users reading the documentation and following it exactly (i.e. putting the environment variable as "DISOCRD_WEB_HOOK")
N/A
=> docs: fix spelling in "Creating a Discord webhook"

src/store/model/galaxus.ts
Next Galaxus Patch for changed update selector, this time its Z1cf
tested and verified working in local installation.
=> fix(galaxus): update selector  ( 14.01.2020 07:00 ) 

src/store/model/vsgamers.ts
Fixes issue #1676 partly, for the vsgamers issue, since it was missing the maxPrice function in the config at all, giving false alarms with set price all over the place
Testing done in test enviroment, everything seems to work as expected now.
=> feat(vsgamers): add maxPrice selector

src/store/model/galaxus.ts
Next  and third change today for the update selector this time to .Z1cw
Testing is done, new selector works so far:
=> chore(galaxus): update selector

src/store/model/galaxus.ts
Daily update for the update selector changes on galaxus.
Tested and verified working as of 17:15 GMT+1
=> fix(galaxus): update selector

.github/workflows/ci.yaml, .github/workflows/documentation.yaml, .github/workflows/nightly-release.yaml, .github/workflows/pull-request-lint.yaml, .github/workflows/release.yaml, .github/workflows/stale.yaml
Updates ci names and conditionals for running steps.
=> ci: update names and steps

.github/workflows/nightly-release.yaml, .github/workflows/release.yaml, README.md
=> ci: update verbiage for steps

src/store/model/vuugo.ts
Fixes #1716
Checked against the problem case and added the Out of Stock check
Before:
After:
Works as expected
=> fix(vuugo): add out of stock check

src/config.ts, src/store/model/microcenter.ts
=> fix(microcenter): properly flag in stock items

src/store/model/galaxus.ts
After a weekend without much change, galaxus changed again this afternoon to  .Z1ew 
Checked against current Version 3.4.1, ran without errors / problems
=> fix(galaxus): update selector 

docs/reference/filter.md, src/store/model/nvidia-gb.ts
- Minor changes to the docs for better clarity.
- Fixed hyperlink not working
If you could merge this @jef ASAP that would be great.
=> fix(docs): nvidia store changes

src/web/index.ts
Fixes #1790
there was a ../ missing in index.ts leading to the wrong path / 404 error on trying to access web panel, this is fixxed now
Access is working again, tested and verified
=> fix(web): 404 Error / page not visible

src/store/model/amazon-ca.ts
for maxprice changed for the whole store
Fixes issue #1846 
Local Testing done and verified via CA VPN:
=> fix(amazon-ca): update selector 

src/store/model/nvidia-de.ts, src/store/model/nvidia-es.ts, src/store/model/nvidia-fr.ts
- Updated Nvidia store inStock container text for accurate stock checking
- Tested working with nvidia store when products were live and in stock
=> fix(nvidia): update inStock text

docs/reference/filter.md, src/store/model/index.ts, src/store/model/pcdiga.ts
Adds support for one of the biggest PC retailers in Portugal, PCDiga
Tested locally - price limits working, stock status working.
=> feat(store): add PCDiga.com

docs/reference/filter.md, src/store/model/globaldata.ts, src/store/model/index.ts
Adds support for a major PC retailer in Portugal, Globaldata
Tested locally - stock status working.
Can't get maxPrice since the element has `&nbsp;` to separate thousands, breaking the regex I guess..
=> feat(store): add globaldata

src/store/model/globaldata.ts
Added 3060, 3060ti and and products to Globaldata.
Tested locally.
=> chore(globaldata): add 3060, 3060ti, amd

src/store/model/newegg.ts
I just updated the newegg.ts file with the 3060 links, also added in the names for the new models in the store.ts file
=> chore(newegg): add 3060 links

src/store/model/playstation.ts
Fixes #2093
- Reproduced the issue and verified the fix with the `test:series` series in the `playstation` store.
=> fix(playstation): fix inStock selector

src/store/model/walmart.ts
Fixes the 5900x url for Walmart. It used to be pointing to the 5950x.
Just verified the URL
=> chore(walmart): update 5900x url

docs/reference/filter.md
changed from ps5 to series s and x
=> docs: update Xbox Series S and X price limit desc

Dockerfile
Tests directory is missing in Docker build process.
Fixes #1735. Fixes #2032.
Notification test works now
```
$ docker run -it --rm --env-file ./dotenv local/streetmerchant test:notification:production
> streetmerchant@3.5.0 test:notification:production
> node build/test/functional/test-notification.js
ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.5.0
[6:19:15 PM] info :: ✔ telegram message sent
npm notice 
npm notice New minor version of npm available! 7.6.3 -> 7.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.9.0
npm notice Run npm install -g npm@7.9.0 to update!
npm notice
```
=> fix: add missing tests in Dockerfile

src/store/model/currys.ts
Added series rx6800, rx6800xt and rx6900xt to Currys UK
=> chore(currys): add rx6800, rx6800xt and rx6900xt

docs/reference/filter.md, src/store/model/amd-be.ts, src/store/model/index.ts
=> feat(store): add amd-be store

src/store/model/alternate.ts
There is a false positiv in case of the following html:
```
<div class="row border-bottom">
<div class="col-12 p-3 text-center">
<span class="d-flex justify-content-center align-items-center">
<b style="color: #009824">Auf Lager </b>
</span>
</div>
</div>
<div class="row border-bottom">
<div class="col-12 p-3 text-center">
<div class="font-weight-bold text-center">
Artikel kann derzeit nicht gekauft werden
</div>
</div>
</div>
```
i run the code and dont got the false positive anymore
=> chore(alternate): add new oos label

src/store/model/multicom.ts
Not sure when but multicom.no was updated and I only got out of stock notifications. This fixes it and adds maxPrice functionality. 
Tested with 2 non GPU items and re-ran it several times.
=> chore(multicom): update selectors

src/store/model/amazon-ca.ts, src/store/model/amazon-de.ts, src/store/model/amazon.ts
fixes #2387 
tested with docker local and false alerts disappeared.
=> fix(amazon): false positives for xbox

src/store/model/mediamarkt.ts
fixes #2488 
tested with docker local and it now properly detects the Captcha.
=> chore(mediamarkt): update captcha selector

src/store/model/elkjop.ts
Adds price selectors to elkjop
Tested with 2 non-gpu items with higher than target price and lower than target price.
=> chore(elkjop): update selectors

src/store/model/netonnet-no.ts
Netonnet-no has updated their site, all the buttons now have ID which includes the SKU for the current item. 
I also added price label 
Tested with out of stock GPUs and in stock items (including w/ price in dotenv)
=> chore(netonnet-no): update selectors

src/store/model/computeruniverse.ts
Otherwise after some time it was getting stuck on cloudflare check. Now it seems to recover after some time.
=> chore(computeruniverse): add backoff code

src/store/model/alternate.ts
added a new PS5 bundle to the "alternate" shop
=> chore(alternate): add PS5 bundle

.github/workflows/nightly-release.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml, package-lock.json
- Updates package-lock.json to use version 2
- Remove unnecessary CI permissions
=> chore: update package-lock, remove ci perms

src/store/model/bestbuy.ts
From https://discord.com/channels/773913070665859073/776482351102427196/1319130563176566837
PR to update the selectors
=> chore: update bestbuy selectors

.github/workflows/ci.yaml
Testing removal of cache to see if CI speeds up.
=> ci: remove cache to speed up
