jef/streetmerchant

.github/pull_request_template.md
.github/workflows/ci.yaml
.github/xo-problem-matcher.json
package-lock.json
package.json
src/store/evga.ts
src/store/index.ts

Resolves #17
- Adds EVGA site
- Add problem matcher for linting

feat: add evga (#17)

---

src/index.ts

Resolves #20 
Using `try/catch` around code that throws `TimeoutError` and skipping it.

fix: exception handling `TimeoutError` (#20)

---

src/index.ts

While looking into adding some of the other bestbuy AIBs, I noticed that the loop in `isOutOfStock` will always return the check that coincides with the last value of `Store::oosLabels`. This does not align with the logic in the documentation:  
```Checks if DOM has any out-of-stock related text.```
This PR addresses this issue.
There are many different ways to do this, if you have a cleaner idea in mind, feel free to suggest one. I come from a mostly Java background so I'm unsure if node has a cleaner way to do this.

fix: small error in `isOutOfStock` logic

---

.env.example
src/config.ts
src/index.ts

feat: add email test, fix memory leak

---

src/store/bestbuy.ts

Update bestbuy.ts to include the remaining AIBs Best Buy currently offers.
This includes a change to the `oosLabels` for Best Buy links to include "Coming Soon". The pages we're sporadically changing between sold out + coming soon on occasion on the 3080's launch day. It's stood at Sold Out since, but just in case...

feat: more Best Buy AIBs

---

.env.example
README.md
src/config.ts
src/index.ts
src/notification/index.ts
src/notification/sms.ts

I moved the notification method into the failure section, disabled email notification and watched my phone for incoming SMS

feat: sms notification for usa carriers

---

src/index.ts
src/store/lookup.ts

Closes #68 
Improves performance by keeping the browser open once and closing when the program ends, rather than opening a browser and closing it every store.

perf: browser abstraction (#68)

---

src/store/lookup.ts
src/store/model/bestbuy.ts
src/store/model/store.ts

As-is the bot only has the ability to have 1 `cartUrl` per site.  The problem is, if a site has multiple links (as almost all do now) you can only assign a single `cartUrl`.  With this change, individual `cartUrl` can be assigned to each link.  By moving the `cartUrl` into the `Links:` we can assign individual `cartUrl` addresses when a product is detected.  I found the add to cart URLs for Best Buy and used it as a proof of concept. 
Tested by changing 1 of the Best Buy links to https://www.google.com the bot detected available stock (as expected) but opened the Best Buy add to cart URL instead of the product page.  I also reverted the Best Buy product URL back to the proper URL to ensure it detected no stock as expected.
None

refactor: move `cartUrl` from `Store` to `Link`

---

src/store/lookup.ts
tsconfig.json

Fixes #58 
The issue has been adressed previously, but not been fixed in it's entirety.
This PR fixes the issue by checking for a 429 HTTP response.
I ran the script for about half an hour with only the default configuration enabled.

fix: check response for rate limiting (#58)

---

src/config.ts
src/index.ts
src/store/lookup.ts
src/store/model/index.ts

- Fix `rateLimitTimeout` from not being defaulted
- Refactor browser and store related config to parent objects
Added and removed environment variable `RATE_LIMIT_TIMEOUT` and saw that `nvidia` and other services are being ran back to back.

fix: `rateLimitTimeout` not being defaulted

---

src/index.ts
src/store/lookup.ts
src/util.ts

Adds a delay whenever we get a CAPTCHA. Seems to work well on newegg.
It also moves the sleep functions to a util.ts file

feat: add delay on captcha to try and evade faster

---

src/adblocker.ts
src/index.ts
src/store/lookup.ts
src/util.ts

Plugs a memory leak due to some architectural oversights in the adblocker plugin.
It must be detached manually from every page, or it will keep a stale reference alive and prevent it from being GC'd
Heapdumps and checking via `htop` for memory allocations

fix: memory leak due to adblocker

---

src/notification/email.ts
src/notification/notification.ts
src/notification/sms.ts
src/store/lookup.ts
src/store/model/store.ts

- Includes screenshot for SMS + Email notifications

feat: include screenshot for emails + sms notifications

---

.env-example
README.md
src/config.ts
src/store/lookup.ts

Adds a new config option `IN_STOCK_WAIT_TIME` that controls the amount of time to wait between consecutive requests to the same store if the store has a card in stock. This is to reduce requests to the store during a time when the user is presumably scrambling to check out. Setting it to 0 (the default value) bypasses this feature entirely.
Tested with the in-stock debug cards.

feat: temporarily pause requests if store has stock

---

README.md
src/store/model/index.ts
src/store/model/officedepot.ts

feat(store): add office depot

---

src/store/model/amazon.ts

- Adds additional 3090 cards to Amazon
- Adds a `cartUrl` for all existing and new Amazon cards
Ran locally and verified that new cards were monitored
N/A

feat(store): add amazon cards and `cartUrl`s

---

README.md
src/store/model/adorama.ts
src/store/model/asus.ts
src/store/model/bandh.ts
src/store/model/bestbuy.ts
src/store/model/evga.ts
src/store/model/newegg.ts
src/store/model/nvidia-api.ts
src/store/model/zotac.ts

- Adds additional 3080 and 3090 cards to adorama, asus, bestbuy, b&h, evga, newegg, zotac
- Adds 3090 FE ID for `en-us` on Nvidia API
- Updates existing 3090 cards from `bestbuy` with add to cart link
- Adds `intl=nosplash` to existing 3090 links in `bestbuy`
Ran locally and verified that new cards were monitored
N/A

feat(store): add additional cards to all stores

---

src/store/model/helpers/nvidia.ts
src/store/model/nvidia-api.ts

Follow-up to comment in #314; I think `drLocale` is the correct locale in all instances, e.g. the Nvidia site uses `en-us` for Canada. The only other difference was Poland where #306 will remove `pl_pSl` anyway as it appears to have been a typo.

chore: remove nvidiaLocale

---

README.md
src/store/lookup.ts

Fixes #315, #312
Wrongly was checking for `store.name` instead of `link.url` during refactor of `IN_STOCK_WAIT_TIME`.

fix: in stock wait time

---

src/notification/notification.ts

Fixes output `↗ sending discord message` when no `webHookUrl` defined.

fix(notification): discord false triggers

---

src/store/model/nvidia.ts

* Adding 2060 super debug card for nvidia store
* https://www.nvidia.com/en-us/geforce/graphics-cards/rtx-2060-super/
* Compliments https://github.com/jef/nvidia-snatcher/pull/333 by providing an in-stock card to verify the inStock label configuration matches as expected on the nvidia "product details" pages
* Tested the 2060 super debug card
* N/A

feat(store): nvidia debug card for "product details" page

---

README.md

Adds norway (was previously missing) and updates 3090 and test card statuses. Removes documentation for russia as a supported country as there are no useable product ids and no support generally^.
^ we only use english texts when checking for stock and the russian store uses a different direct-sales-shop endpoint

docs: update supported countries

---

src/store/model/nvidia-api.ts

norway currency should be `NOK` not `EUR`
norway drLocale should be `no_no` not `nb_no`
_3080 example:_
Previous API url that nvidia.ts would call ended up beeing: 
https://api-prod.nvidia.com/direct-sales-shop/DR/products/nb_no/EUR/5438797200
this URL ends in **status: "failure"**
New fixed API url that nvidia.ts is calling: 
https://api-prod.nvidia.com/direct-sales-shop/DR/products/no_no/NOK/5438797200
This URL is correct
Tested with no errors

fix: corrected norway locales

---

src/config.ts

fix: `envOrNumber` behavior

---

src/store/model/asus.ts

Fixes #382
Verified link is working fine in the snatcher by running it locally for hours. 
Not sure on link for regular Asus Strix 3080 otherwise I would have added it.

feat(store): add asus strix oc to asus store

---

src/store/model/newegg.ts

3090 ftw3 and ftw3 ultra were listed as ftw3 gaming and ftw3 ultra gaming. Removed gaming to bring them inline with the model name used everywhere else (as far as I can find).

chore: normalize ftw3 naming

---

src/store/model/gamestop.ts

Fixed issue where gamestop would generate false positives because the string add to cart was still included even when there was no stock available.  Just added the outOfStock label to look for not available, which is actually displayed on the button.
Fixes #392
Before the fix, as soon as I ran the bot, a notification would be created for gamestop having stock.  After the fix, the info log note shows gamestop out of stock as well.  Ran it for a at least 10 to 20 minutes with no issues.
Before
After

fix: gamestop false positives

---

src/store/model/bandh.ts

processBackoffDelay only triggers with status codes 403.
I was getting a lot of RATE LIMIT EXCEEDEDs from B&H.  
In lookupCard, however, it does check for 429 and logs it as a warning.
```
if (statusCode === 429) {
Logger.warn(Print.rateLimit(link, store, true));
```
I figure that getting these RATE LIMIT EXCEEDEDs is bad and it should trigger a backoff, so I added 429 to bandh.ts to the backoffStatusCodes: [403, 429] array/list.
A lot less RATE LIMIT EXCEEDEDs
I've been running it with the added 429 and it's been running fine for the last few hours with no issues.  Less RATE LIMIT EXCEEDEDs.
edit: code formatting

fix: add status code `429` to bandh `backOffStatusCodes`

---

src/store/model/newegg-ca.ts

Adds EVGA 3090 xc3 ultra, xc3, ftw3 ultra and ftw3 to newegg.ca
Fixes #388  kind of, there are currently no evga 3090 cards listed on bestbuy.ca         
Ran snatcher only looking for evga 3090 products and verified all links work.

feat(store): add evga 3090 to newegg canada

---

README.md
src/store/model/bestbuy.ts

Fixes #423
Adds 3080 xc3, ftw3, ftw3 ultra, aorus master, vision and 3090 ftw3, ftw3 ultra
Adds vision to readme list of models

feat(store): add models to bestbuy

---

src/store/model/amazon-de.ts
src/store/model/asus-de.ts
src/store/model/index.ts

Closes #412 and #435 
tested the german asus webstore with ASUS ROG-STRIX-RTX2060S-O8G-EVO-V2-GAMING and worked like it should.

feat: add asus-de store and asus 3080 tuf/oc to amazon-de

---

src/store/model/newegg-ca.ts
src/store/model/newegg.ts

Fixes #400 
Verified updated `inStock` and `maxPrice` selectors are working correctly, running against multiple products and price ranges for both stores (newegg and newegg-ca)

fix(store): update `inStock` and `maxPrice` for newegg, newegg-ca

---

src/config.ts

feat: Add ATT prepaid to supported carriers.
Added ATT Prepaid SMS notifications support.
Ran notification test, received text on my cell phone on ATT Prepaid.

feat(notification): add at&t prepaid carrier

---

src/store/model/nvidia-api.ts

Change US 2060 SuperID to Nvidia Shield ID
https://i.imgur.com/WIBoV9K.png
Fixes #407 to allow for better testing of the Nvidia API. Since the 2060 super was out of stock the Shield TV id would fix out of stock tests
Motivation: Hacktoberfest
In truth I don't know how to go about testing this project, but I figure this is a simple enough change. I also did ensure that the ShieldTV ID was what is linked in the ticket:
https://i.imgur.com/WIBoV9K.png

chore: update `nvidia-api` test with shield tv

---

README.md
src/index.ts
src/logger.ts

Adds `meta` to logger so that we can add extra meta info and format it correctly.
We should also include `error` in the future.

feat: add `meta` to logger

---

README.md
src/index.ts
src/store/fetch-links.ts
src/store/lookup.ts
src/store/model/amazon-uk.ts
src/store/model/aria.ts
src/store/model/box.ts
src/store/model/ccl.ts
src/store/model/currys.ts
src/store/model/ebuyer.ts
src/store/model/helpers/card.ts
src/store/model/index.ts
src/store/model/novatech.ts
src/store/model/overclockers.ts
src/store/model/scan.ts
src/store/model/store.ts
src/store/model/very.ts

**Relates to #461 - merge second**
This adds 10 UK stores, I've not added `maxPrice` yet but plan to do so in a future PR. https://github.com/andrewmackrodt/nvidia-snatcher/compare/pr-framework-updates...pr-uk-stores

feat: add uk stores

---

README.md
src/config.ts
src/store/model/microcenter.ts

Resolves #386 
In some cases (e.g. Georgia) there are more than one MicroCenter locations nearby, so we'd want to check more than one location.
Set MICROCENTER_LOCATION variable to "duluth,marietta" and STORES to "microcenter". Verified in the debug logs that links from both locations were loaded into the Store object for MicroCenter. The bot then checked for cards from MicroCenter successfully.

feat: allow multiple microcenter locations

---

README.md
src/store/model/index.ts
src/store/model/proshop-dk.ts

feat: add proshop-dk

---

src/store/includes-labels.ts

Currently the labels text to be searched must only be in lowercase for the search in DOM text to work successfully. If the provided labels text has uppercase letters, it will not be matched successfully. 
Some contributors might not know about this restriction and may set text containing uppercase letters.
With this commit, It should be possible to have uppercase letters in the labels text. This change should be backwards compatible, and should work for both cases with labels having lower case letters or upper case letters.
If you set some label text that contains any uppercase letter, it will not be found in the DOM text because the DOM text is being lowercased before search and match while the label text is not lowercased. With this change we lowercase the label text too before …

fix: add support for stores label text to have uppercase letters

---

README.md
src/config.ts
src/store/lookup.ts

Added the ability to use Incognito tabs.
At least with chrome, it uses a cache for sites, incognito forces to reload everything.
This might help better detect when the "add to cart" button is updated.
Tested with a normal link with "headless:false" to see if it actually opens in "incognito" and it does.

feat: add incognito mode

---

README.md

Purely an informational change for anyone looking to filter by Gigabyte's Vision OC card. Following the readme's filter guide for this model results in a filter for a card that doesn't exist.
Running this while filtering by `gigabyte` brand results in searches for `vision oc` cards (along with other Gigabyte cards, as expected), but filtering by the `vision` model like the readme says doesn't result in any searches. Filtering by the `vision oc` model works as expected.

fix: update gigabyte model `vision oc`

---

README.md
src/store/model/amazon-es.ts
src/store/model/index.ts
src/store/model/pccomponentes.ts

Added spanish PCComponentes and Amazon-ES stores to the store list along with their product links and stock status states.

feat(store): Add PCComponentes and Amazon-ES Stores.

---

src/store/model/scan.ts

Add a ttl to refresh scan store links every 5m. This is due to the founders card links being intermittently available. Currently the page is 404 but it was active yesterday when the cards went up. Credit to andrew on discord for the suggestion.
https://www.scan.co.uk/shops/nvidia/3090-founders-edition
Tested running snatcher locally with Scan enabled.
None.

feat(store): add ttl for `scan`

---

README.md

The [native installation instructions](https://github.com/jef/nvidia-snatcher#native-installation) in the readme have `.env.example` as the name of the example env file, where the file is actually called `.env-example`. This PR updates this section of the readme to use the correct filename.
N/A
N/A

docs: readme install instructions typo

---

src/store/model/notebooksbilliger.ts

Notebooksbilliger seems to be the (official) retailer for german FE drops now.
Fixes #584

feat(store): add founders editions to notebooksbilliger.de

---

README.md
src/config.ts
src/store/filter.ts
src/store/model/index.ts

Possibility to filter additionally a model by a series.
**Use-Case:**
Searching for 3 cards: the founders edition 3090, asus strix oc 3080 and 3090.
Both models are generally available for both series. (e.g founders edition 3080, founders edition 3090 etc.)
**Example Config for Use-Case:**
STORES="asus,nvidia"
SHOW_ONLY_BRANDS="asus, nvidia"
SHOW_ONLY_MODELS="rog strix oc, founders edition:3090"
Result:
nvidia-snatcher searches for: rog strix oc 3080, rog strix oc 3090, founders edition 3090
**Limitations**
Additional filtering only works for series that are globally enabled and not filtered out by SHOW_ONLY_SERIES.

feat: allow filtering per model by a specific series

---

src/notification/discord.ts

Currently the Discord notification does not show whether the card in stock is a 3080 or 3090.
I ran `npm run test:notification`. Seems to work as intended.

feat: add series to Discord webhook

---

src/store/model/asus.ts

Fixes #633 
Derived from Newegg API realtime lookup code structure 
Tested against in-stock 5700xt and out-of-stock 3070. Does not interfere with normal operation.
None

feat(asus): realtime api

---

src/store/model/notebooksbilliger.ts

Notebooksbilliger created another article page for each Founders Edition series.
This adds the new links for the 3070, 3080, and 3090 FE.
I temporarily added the url to the end of buildProductString to verify it is looking up multiple links of the same card on one site.
This may could further be improved by allowing an array of url's in the Link model. But that would need more changes.

chore(notebooksbilliger): add more FE links

---

src/store/model/alternate.ts
src/store/model/amazon-de.ts
src/store/model/caseking.ts
src/store/model/computeruniverse.ts
src/store/model/cyberport.ts
src/store/model/mindfactory.ts
src/store/model/notebooksbilliger.ts
src/store/model/proshop-de.ts

I added the zen 3 processors to some german stores: alternate, amazon-de, caseking, computeruniverse, cyberport, mindfactory (only 5600x and 5800x, I could not finde the other links), notebooksbilliger, proshop-de .
I let the streetmerchant check the stock for the zen 3 processors on these stores and it worked fine.

feat(store): add zen 3 to german stores

---

README.md
src/config.ts
src/store/model/amazon.ts
src/store/model/bestbuy.ts
src/store/model/gamestop.ts
src/store/model/index.ts
src/store/model/store.ts
src/store/model/target.ts
src/store/model/walmart.ts

- Add PS5 Console and PS5 Digital Edition support
- Add Walmart, Target stores

feat(ps5): add console and digital edition

---

src/store/model/alternate.ts
src/store/model/amazon-de.ts
src/store/model/mediamarkt.ts
src/store/model/saturn.ts

I added the PS5 to the German stores alternate, amazon-de, mediamarkt and saturn.
Seemed to work fine:

feat(store): add ps5 to german stores

---

src/store/model/mindfactory.ts

The two higher tier Ryzen5000 models were missing from the mindfactory.ts file
None tbh, however links are the official ones taken from their [Ryzen5000 Series overview / FarCr6 Bundle page](https://www.mindfactory.de/Highlights/AMD_Ryzen_Game_Bundle_FarCry6/Badge/163x80_badge_AMD_Ryzen_Game_Bundle_FarCry6_NEW).
None

feat(mindfactory): add ryzen 5900x, 5950x

---

README.md
src/store/model/amd-de.ts
src/store/model/arlt.ts
src/store/model/index.ts

I have added the store Arlt with some 3070s, 3080s, 3090s and the zen 3 processors. I have also added the german AMD as a store with the zen 3 processors.
I tested the status check for Arlt and AMD-de and I tested the price recognition for Arlt with 3 and 4 digit numbers.

feat(store): add `arlt` and `amd-de`

---

src/store/model/amazon.ts

Adds a few 3070s on amazon-us
NEW: 
Model for pny: xlr8 uprising
Model for asus: dual (there's two pages for this model at the moment, I went with the less sketchy looking one) 
Only tested OOS logic, couldn't verify in-stock for obvious reasons
~~I was running into some error logs for a PNY card, but it appears to be related to the e-buyer automatic link generation, who's logic doesn't apply to amazon cards~~ Unrelated issue per #694

feat(amazon): add more 3070s

---

README.md
src/store/model/amazon-uk.ts
src/store/model/ebuyer.ts
src/store/model/game.ts
src/store/model/index.ts
src/store/model/scan.ts

Adds support for the following:
- Add new store: game (Game UK)
- Add PS5 links for amazon-uk, ebuyer, scan, game
- All added new links are currently working and reporting back correctly
- Game UK store tested with item conditions: Buy New, Pre-order, out of stock.

feat(store): add `game` store, add ps5 for uk stores

---

README.md

docs: Added an example of how to add a zen3 cpu to the filter to the readme.
I noticed that I got the syntax for adding a Ryzen cpu to the filter wrong and thought the readme could use a subtle update to show how to do it. 
N/A

docs: add zen3 filter to `SHOW_ONLY_SERIES`

---

README.md
package.json
src/config.ts
src/notification/sms.ts

Fixes https://github.com/jef/streetmerchant/issues/273.
Update to stale pull request https://github.com/jef/streetmerchant/pull/446
Multiple carriers & phone numbers are now supported in the .env file.   Number of carriers must strictly match the number of phone numbers (documented in readme)
Error handling was changed a bit in sms.ts:
- if number of carriers does not match number of phones (even if one is 0), logger will warn
- if there is a difference in `carrier.length` or `number.length`, sendSms will say:
> (carrier) is not associated with a number
or
> (number) is not associated with a carrier
- phone.availableCarriers.has(carrier) has been moved to trigger a logging error inside of sendSms, and this logging function has been removed from generateAddress
- any of these above errors …

feat(notification): support for multiple phone numbers

---

src/store/model/walmart.ts

`ps5 console` and `ps5 digital` models both incorrectly shared the same URL in the Walmart model.
This PR corrects `ps5 digital` URL to point to the correct product page.

fix(walmart): ps5 digital url

---

src/notification/discord.ts

Due to popular demand, add both the product page link and ATC link to the discord embed when a product is in stock.
Tested with the amazon test card when a ATC link is and isn't defined.

feat(discord): add cart link to embed

---

src/store/model/newegg.ts

Adds the Gigabyte 3080 VISION OC to Newegg's list.

chore(newegg): add 3080 vision oc

---

src/store/model/asus.ts

Fixes #789 
I added 503, plus the usual signals that we're getting rate limited, since I'm getting that constantly after 1-2 successful
requests. Works fine when adding this status code.
Add `asus` to the `STORES` env var. Before this PR I was getting 503s after a minute or two, and now it receives a 503, backs off, and scrapes more slowly. No more 503s!

feat(asus): add backoff codes

---

README.md
src/store/model/index.ts
src/store/model/playstation.ts

- Add PlayStation store for PS5 consoles (closes #804)
I have not added support for the `outOfStock` label, due to Playstation store output both 'Add', and 'Out of Stock' where the appropriate stock label is then hidden on load. `lookupCardInStock` config is set to `requireVisible: true` for the `inStock` label but not any other label, meaning I can only implement an `inStock` label alongside using `realTimeInventoryLookup` for validation.

feat(store): add `PlayStation` store

---

src/store/model/playstation.ts

- Added outOfStock label to PlayStation store by using `:not(.hide)` class selector - closes #809

feat(playstation): add `outOfStock` label

---

src/config.ts

When using multiple strings split by `\n` for `USER_AGENT`, user agents end up being split by `,` due to `\n` not being escaped properly.
Given the following in `.env`:
USER_AGENT=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36 \n Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0 \n Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
`config.userAgents` becomes:
[
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML',
'like Gecko) Chrome/86.0.4240.193 Safari/537.36 \\n Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0 \\n Mozilla/5.0 (Macintosh; Intel Mac OS X …

fix(config): correcting newline split for multiple user agents

---

src/store/model/newegg-ca.ts

Partially addresses #808 , user linked some Canadian store URLs 
Ran the bot on windows with
```
SHOW_ONLY_SERIES=rx6800,rx6800xt
STORES=newegg-ca
```

feat(newegg-ca): add big navi links

---

src/store/model/amazon.ts
src/store/model/store.ts

Fixes #(879)
Adds Big Navi links for Amazon (US)
Ran with these new entries and had no issues.

chore(amazon): add big navi links

---

src/config.ts
src/store/model/amazon.ts
src/store/model/bandh.ts
src/store/model/bestbuy.ts
src/store/model/corsair.ts
src/store/model/index.ts
src/store/model/store.ts

improvement: Allow monitoring of corsair sfx power supplies
Fixes #758 
Adds support for corsair sf series (750, 600), at Best Buy, BandH, Amazon
Adds Corsair store
add corsair as brand in .env
add stores: amazon, bandh, bestbuy, corsair
run

feat(store): add corsair sfx PSUs

---

src/store/model/memoryexpress.ts

Some products can be "Backorder" on MemoryExpress, so it shouldn't appear as "In Stock". 
Perhaps, it could be a seperate label in the future?
The [Ryzen 5600x](https://www.memoryexpress.com/Products/MX00114455) is currently "Backorder" and will show as "In Stock" on streetmerchant

fix(memoryexpress): add backorder to `outOfStock` selector

---

src/store/model/newegg.ts

Original URL resolved properly due to Item# being correct, but my OCD noticed the URL was referencing the 5900x :)

fix(newegg): typo in 5800x url

---

src/store/model/amazon-it.ts
src/store/model/comet.ts
src/store/model/euronics.ts
src/store/model/index.ts
src/store/model/unieuro.ts

This PR add 4 Italian stores, namely [Uniero](https://www.unieuro.it), [Euronics](https://www.euronics.it), [Amazon-it](https://www.amazon.it), [Comet](https://www.comet.it). I only add, for now, the PlayStation 5 links for both versions. I do not check each one of the streetmerchant supported items, but I suspect that most of them do not even have a page in those stores. However, if you are interested in it, I can try to complete the store files as much as possible. 
Close #972
Close #956
I test the in-stock check by using some other available products for each store.

feat(store): add some italian stores with ps5 links

---

src/store/model/scan.ts

There isn't an issue for this as its so small but related products were being picked up on scan. I've just changed the css selector to filter out these.
Just changed `ul.productColumns` to `ul.productColumns:not(.related)`.
Tests weren't really necessary for this, related products were no longer picked up by the scraper. I'm not super confident in writing them but I can give it a try if its that necessary.

fix: related products being picked up on scan

---

src/store/model/amd.ts

Adds the RX 6800 (non-XT) card from the AMD Direct store; only the 6800XT is available currently.
1. Ran tracking with `STORES=amd` and `SHOW_ONLY_SERIES=rx6800`.
2. Verified `OUT OF STOCK` response.

chore(amd): add rx6800

---

src/store/model/alternate.ts
src/store/model/amazon-de.ts
src/store/model/amazon-es.ts
src/store/model/amazon-fr.ts
src/store/model/amazon-uk.ts
src/store/model/computeruniverse.ts
src/store/model/cyberport.ts
src/store/model/mediamarkt.ts
src/store/model/saturn.ts

Update Alternate, Amazon DE, Amazon ES, Amazon FR, Amazon UK, Computeruniverse, Cyberport, Mediamarkt, Saturn urls.
Includes all urls for PS5 digital or disc version, XBox Series X and XBox Series S whenever found.
Update outOfStock identificator for Alternate, Amazon DE, Amazon ES, Amazon FR, Computeruniverse and Saturn.

chore(store): add xbox/ps5 to eu stores

---

README.md

The xbox model values for the environment variables are currently provided as `xboxsx` and `xboxss`. These are incorrect. This branch updates the `README.md` file to correct these values as follows: `xbox series x` and `xbox series s`.
- Started and ran `streetmerchant` with the following environment variable as described in the current README.md:
```SHOW_ONLY_MODELS="xboxsx,xboxss"```
- The logs did not provide any reporting on xbox devices
- Started and ran `streetmerchant` with the following environment variable as a hunch:
```SHOW_ONLY_MODELS="xbox series x,xbox series s"```
- This provided reporting on both xbox devices
Enviroment [`.env`] file used:
```
ASCII_BANNER=""
ASCII_COLOR=""
COUNTRY="usa"
SHOW_ONLY_BRANDS="microsoft"
SHOW_ONLY_MODELS="xbox series x,xbox series s" …
```

dics: correct model values for xbox

---

src/store/model/bestbuy-ca.ts

I've been mainly using this tool to search for an EVGA XC3 3080 in Canada. A few times I noticed that while other resources such as twitter and /r/bapcsalescanada notified stock for this item, street merchant never caught it even though it was running. At first I figured it must have been some latency or another issue.
However, it has come to my attention that bestbuy.ca has two links for this product:
https://www.bestbuy.ca/en-ca/product/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x-video-card-english/14961449
https://www.bestbuy.ca/en-ca/product/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x-video-card/15084753?intl=nosplash
The first link is what is currently stored in the codebase. However, the following resources suggest that it is the second link that is seeing restocking. …

fix(bestbuy-ca): replace old evga xc3 ultra

---

README.md
src/store/model/index.ts
src/store/model/otto.ts

Add support for Otto. Allow checking of PS5 disc and digital version availability, as well as XBox Series X and S.
Two PS5 disc version urls are included as they take the sale url offline once the item is sold out, so I couldn't test out which is the current url.

feat(store): add Otto

---

src/store/model/zotac.ts

Adds the RTX 3060 Ti and 3070 cards from the Zotac Online Store.
1. Ran tracking with `STORES=zotac` and `SHOW_ONLY_SERIES=3060ti,3070`.
2. Verified `OUT OF STOCK` response.

chore(zotac): add 3060ti, 3070

---

src/store/model/bestbuy-ca.ts

Fixes #1093
It seams that the page changed to always include the "Add to cart button". However, when there is no card in stock, that button is disabled. I used the class applied on the button when there is no items in stock to fix the issue.
I tried with the test URL and with some cards that where not in stock. The same class is added to the button when the product is not in stock.
Hope it helps !

fix(bestbuy-ca): model always indicating in stock

---

src/store/model/amazon.ts
src/store/model/bestbuy.ts
src/store/model/store.ts

This pull request addresses and fully resolves #1098 and resolves #1160. This also adds the missing required AIB model to store.ts. This also addresses an issue in bestbuy.ts where an rx6800 card was reporting as an rx6800xt.

chore(amazon): adds most available AIB cards

---

README.md
src/store/model/elcorteingles.ts
src/store/model/index.ts

Add El Corte Ingles with PS5 and Xbox Series X/S support.

feat(store): add el corte ingles

---

package-lock.json
package.json
src/__test__/notification-test.ts
src/config.ts
src/logger.ts
src/notification/discord.ts
src/store/includes-labels.ts
src/store/lookup.ts
src/store/model/amazon-ca.ts
src/store/model/amazon-es.ts
src/store/model/amazon-fr.ts
src/store/model/amazon-it.ts
src/store/model/amazon-nl.ts
src/store/model/amazon-uk.ts
src/store/model/amazon.ts
src/store/model/index.ts
src/store/model/store.ts

Resolves #1188
Resolves #673
Resolves #1187
- Gives the ability to put price into notifications (and potentially other places?)
- Update Discord notification information
- Resolves issue that did not let users know why it's out of stock (captcha or banned seller)
- Update amazon's test item
- Update amazon's price selector
- Remove deprecation notice for nvidia outside of USA
- Unsure if `nvidia` is _actually_ superseded by `bestbuy`
- Removed `discord-webhook-node` in favor of more popular library `discord.js`

feat(notification): add price to links

---

src/store/model/amazon-it.ts

Fixes issues #1237 #1238 
The `amazon-it` store is now updated to fix some bugs
- Fixed price parsing using the correct decimal separator
- Fixed an Asus 3070 Dual url, which pointer to an Amazon Fire Stick instead

fix(amazon-it): maxPrice selector and links

---

src/store/model/amazon.ts

added support for 3060ti cards on amazon on amazon.ts 
Only modified src/store/model/amazon.ts
NA

chore(amazon): add 3060ti cards

---

docs/reference/filter.md
src/store/model/index.ts
src/store/model/megekko.ts
src/store/model/store.ts

feat: Megekko (NL) added to the existing stores.
- Added 1 new store: Megekko (NL). Currently only products listed are from the RTX 3080 Series.
- Also added a few new models for RTX 3080.

feat(store): add Megekko

---

src/store/model/amazon-it.ts
src/store/model/eprice.ts
src/store/model/unieuro.ts

Fix some issues on some Italian store.
In particular:
- ePrice store sometimes products where show wrongly in stock
- Amazon-it do not correctly see the caption page
- Uniero return a blank page after too many requests
I used the trick on issue #1194 to always save a screenshot. Maybe it can be useful to have a configuration option to do that.

fix(store): italian store checks

---

src/store/model/newegg.ts
src/store/model/store.ts

**Added:**
Powercolor Red Devil and Red Dragon models for RX6800 on newegg usa
Powercolor Red Dragon 
**Testing:**
test was done using fresh pull after this commit in new directory.
commands:
```
npm install
npm run start
```
relevant .env config:
```
SHOW_ONLY_SERIES="rx6800xt,rx6800"
STORES="newegg"
SHOW_ONLY_MODELS="red devil, red dragon"
```

chore(newegg): add powercolor red devil, red dragon

---

docs/reference/notification.md
src/config.ts
src/notification/sound.ts

Allows the default sound player to be overridden. I was having trouble on Ubuntu with the default player which sound-player chose.
Ran locally
None

feat(notification): add sound player executable option

---

src/store/lookup.ts

fixes #1311
Fixes #826
stops puppeteer exiting with exitcode 1
please head over to #1311 to see the detailed description
couldn't run streetmerchant 24/7 without  `await page.setRequestInterception(true);` 
no new dependencies

fix: add setRequestInterception

---

.github/ISSUE_TEMPLATE/bug-report.md
.gitignore
docs/getting-started.md
docs/help/troubleshoot.md
dotenv-example
nodemon.json
src/config.ts
src/index.ts
src/notification/mqtt.ts

Refactored `.env` to be `dotenv` now. `.env` will still work until we release 4.0.0; then neither will work as it's a whole different system.
This is done because there are many cases where new users cannot find this file or have problems doing so. This should enable them to find and customize streetmerchant much easier.
Local testing, seems to be working fine.

refactor: change `.env` to be `dotenv`

---

src/store/model/amazon-uk.ts
src/store/model/amd-uk.ts
src/store/model/argos.ts
src/store/model/aria.ts
src/store/model/awd.ts
src/store/model/box.ts
src/store/model/ccl.ts
src/store/model/currys.ts
src/store/model/ebuyer.ts
src/store/model/game.ts
src/store/model/helpers/card.ts
src/store/model/index.ts
src/store/model/overclockers.ts
src/store/model/scan.ts

Fixes #1348 
**New features:**
- **AMD-UK**: New store that scans for all Ryzen 5000 and RX 6000 series products.
**Bug fixes and improvements:**
- **Amazon-UK**: Add RTX 3070.
- **Argos**: Updated PS5 links. Add Xbox Series S/X.
- **Aria**: Add RTX 3070. Remove duplicate 3060ti link builder.
- **AWD-IT**: Updated container labels to more accurately parse info. Remove hard-coded links in favour of link builders. Add RX 6800/XT series. Remove duplicate RTX 3060Ti link builder.
- **Box**: Add backoffstatuscodes. Update price and outOfStock container labels. Add PS5 and Xbox Series S/X models. Add RX6900XT model.
- **CCL**: Add RX 6900XT.
- **Currys**: Remove duplicate RTX 3060ti link builder. Add PS5 and Xbox Series S/X consoles.
- **eBuyer**: Update labels. Add Xbox Series S/X consoles. …

fix(store): update UK stores

---

docs/reference/filter.md
src/store/model/argos-ie.ts
src/store/model/gamestop-ie.ts
src/store/model/harveynorman-ie.ts
src/store/model/index.ts
src/store/model/smythstoys-ie.ts
src/store/model/tesco-ie.ts

Added the following Irish variants of stores to this bot:
- [Gamestop](https://gamestop.ie)
- [Argos](https://argos.ie)
- [Harvey Norman](https://harveynorman.ie)
- [Smyths](https://smyths.ie)
- [Tesco](https://tesco.ie)
Tested locally against the various new stores that were added in this PR.
N/A

feat(store): add Irish store variants

---

docs/reference/application.md
docs/reference/proxy.md
src/config.ts

This allows to have one main proxy list that all stores can load from (some users have asked for this feature)

feat(proxy): fallback to a global proxy list

---

src/store/lookup.ts

Checking for Out of Stock before checking for max Price
Fixes #1421
Tested it briefly on Ubuntu Desktop 20.04 and it worked
none

fix(lookup): check out of stock before price

---

.gitignore
package-lock.json
package.json
src/store/lookup.ts
src/util.ts

As you might notice, I had to fork puppeteer-page-proxy. The fix I applied has already been PR'd upstream for several months and the library seems unmaintained currently (but there is no viable alternative either).
Other than that, I also added the `*.proxies` files to gitignore and fixed a problem where adblock would "randomly" disable request interception.

fix(proxy): fix requests with proxies

---

src/logger.ts
src/store/lookup.ts

Resolves #1297 
- Move response handling to a function that can be called recursively
- Check 503 responses for Cloudflare's "attribution" div + link text
- If we hit a Cloudflare page, do page.waitForNavigation and then call response handling again (recursively)
Set store = "zotac"
Set brand & model = ""
Set series = "3070, 3080, 3090"
Run and observe output
Prior result: Frequent 503 errors due to Cloudflare protection
New result: Periodic "CLOUDFLARE, WAITING" message followed shortly by success (typically OUT OF STOCK)

feat(lookup): handle Cloudflare DDoS protection

---

docs/reference/filter.md

Add MAX_PRICE reference docs for AMD 6800, 6800xt, 6900xt GPUs
N/A
N/A

docs(reference): add AMD 6800, 6800xt, 6900xt

---

docs/reference/filter.md

The store `AWD-IT` is missing from the documentation. 
This PR adds the missing store to the docs.

docs(reference): add AWD-IT

---

docs/reference/filter.md
src/store/model/index.ts
src/store/model/johnlewis.ts
src/store/model/shopto.ts

- **John Lewis**: Add support for ps5 console
- **ShopTo**: Add support for ps5 console and digital edition
Resolves #977

feat(store): add `johnlewis` store, add `shopto` store

---

src/store/model/amazon-uk.ts
src/store/model/ebuyer.ts

Fixes #1485 
- Amazon-UK: RTX cards were not being parsed correctly. Use hard-coded links for better reliability
- eBuyer: PS5 consoles links updated
- Scan for RTX cards at Amazon
- Scan for consoles at eBuyer
- They should usually show OUT OF STOCK and show IN STOCK when available

fix(store): link builder in UK stores

---

src/config.ts

The array of stores by default contains two shops in one entry. To fix this, you must enter both shops as separate entries.
**[11:19:59 AM] warn :: No store named amazon,bestbuy, skipping.**
[11:19:59 AM] info :: ℹ selected stores: amazon,bestbuy
[11:19:59 AM] info :: ℹ selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx
**[11:25:15 AM] info :: ℹ selected stores: amazon, bestbuy**
[11:25:15 AM] info :: ℹ selected series: 3060ti, 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx
[11:25:28 AM] info :: ✖ [amazon] [asus (3080)] strix :: OUT OF STOCK
[11:25:31 AM] info :: ✖ [amazon] [msi (3080)] gaming x trio :: OUT OF …

fix: properly pass array entries as separate indices

---

docs/reference/filter.md
src/store/model/equippr.ts
src/store/model/futurex.ts
src/store/model/index.ts

New store for German region - equippr.de and future-x.de with support for several Nvidia RTX 3060ti, 3070 and 3080.
Edit the `dotenv` or `.env` to add the new store:
```
...
STORES=equippr,futurex
```
Sample Log: 
```
➜  ~ pm2 logs | grep equippr
0|Merchant | [9:43:33 AM] info :: ✖ [equippr] [msi (3060ti)] ventus 2x :: OUT OF STOCK
0|Merchant | [9:43:40 AM] info :: ✖ [equippr] [zotac (3070)] twin edge oc :: OUT OF STOCK
0|Merchant | [9:43:48 AM] info :: ✖ [equippr] [zotac (3070)] twin edge :: OUT OF STOCK
0|Merchant | [9:43:55 AM] info :: ✖ [equippr] [gigabyte (3070)] eagle :: OUT OF STOCK
0|Merchant | [9:44:00 AM] info :: ✖ [equippr] [gigabyte (3070)] eagle oc :: OUT OF STOCK
```

feat(store): add equippr & futurex for DE region

---

src/store/model/amazon-de-warehouse.ts

Fixes #1500
maxPrice selector was not matching properly for warehouse listings.
Create a link in amazon-de-warehouse.ts targeting a product that has warehouse listings
Set MAX_PRICE for the link's defined product to something less than the lowest warehouse listing
Run
None

fix(amazon-de-warehouse): update wrong maxPrice selector

---

src/notification/philips-hue.ts

Super minor change to the log output, it seems the text for these two blocks of the if/else were using the opposite verbiage
Simply hooked up the Hue config and observed the log output locally

chore(philips-hue): correct the log text

---

src/notification/pushover.ts

Include screenshot image to pushover if it exists (similar to email notification), since pushover is capable of receiving image. On iOS, we can long tap or pull down to see an overview. 
Feel free to make any changes if required or close this if not.
No test done, since I don't use the app (nor the package) and I don't know how to test it too. Please help to code review.

feat(pushover): add screenshot to push notification if available

---

docs/reference/filter.md
src/store/model/index.ts
src/store/model/store.ts
src/store/model/vuugo.ts

Added an additional Canadian store Vuugo with support for all available RTX 3000 series, RX 6000 series and Ryzen 5000 series components.
Also added two additional GPU Models which were available at Vuugo but not previously added
- [Asus EKWB](https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-RTX3080-10G-EK.html)
- [PNY XLR8 Epic-X](https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG308010TFXPPB.html)
Edited the env confirmation to add the new store:
```
...  
STORES=vuugo  
...
```
Ran the application to verify stock was checked including the test item
```
[2:51:22 p.m.] info :: 🚀🚨 [vuugo] [test:brand (test:series)] test:model :: IN STOCK 🚨🚀  
https://www.vuugo.com/computer-hardware/computer-parts/hard-drives/seagate-har …
```

feat(store): add GPU and CPU support for Vuugo

---

src/store/model/mediamarkt.ts
src/store/model/saturn.ts

fix(store): update out of stock detection for MediaMarkt and Saturn

---

src/store/model/galaxus.ts

fix: Galaxus again changed the CSS marker for the product_details changed once before 2 days ago
Galaxus changed once more the CSS marker on the site, last time on 30.12. ( opened pull request #1568 , which as not processed in the meantime and got closed by me ) and beforehand as fixxed around a week ago from knotenjoe in #1469 
Script  runs fine with the replaced CSS marker and pulls the correct price from the site again.

fix(galaxus): update selector

---

src/store/model/bestbuy-ca.ts
src/store/model/canadacomputers.ts
src/store/model/memoryexpress.ts
src/store/model/newegg-ca.ts

Fixes #1513 and fixes #1371 
I noticed multiple different CPUs/GPUs were not present in several different Canadian retailers, I went through the list of them and added the missing cards and removed some dead links (which caused the issue in #1513). While doing so, I noticed many Twin Edge, TUF, Aourus Master and Eagle cards were mis-categorized or were missing the oc suffix.
amazon-ca wasn't updated as a part of this, finding cards is a bit of a mess right now as amazon tends to hide products with no stock in strange ways.
I've been running this branch for ~24 hours now and haven't identified any issues. The new cards are being searched and old cards are now searched under the correct category (the issue in #1371)

fix(store): update missing/mislabeled cards for Canadian retailers

---

web/index.html

Fixes an issue where the HTML labels on the web control don't get their `for` attributes set, which means you cannot click on the labels to control the checkboxes. This change uses `setAttribute` to set the `for` attribute correctly.
1. Before this PR, click a label in the web control. Notice that it DOESN'T toggle the corresponding checkbox.
2. After this PR, click a label in the web control. Notice that it DOES toggle the corresponding checkbox.

feat(web): properly set `for` attribute for labels

---

src/store/model/asus.ts
src/store/model/store.ts

Updates the links for 30 series cards on store.asus.com and adds the ASUS 'ko oc' as a Model variant.
Testing complete by @wofnull and @kiowadriver in Issue #1637.

fix(store): Update 30 series links and models for store.asus.com

---

src/store/model/asus.ts

Resolves #368
Add `outOfStock` label to help lessen false-positives.
```
ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.3.0
[12:09:03 PM] info :: ℹ selected stores: asus
[12:09:03 PM] info :: ℹ selected series: test:series, 3060ti
[12:09:18 PM] info :: 🚀🚨 [asus] [test:brand (test:series)] test:model :: IN STOCK 🚨🚀
https://store.asus.com/us/item/202006AM260000003
[12:09:21 PM] info :: ✖ [asus] [asus (3060ti)] tuf oc :: OUT OF STOCK
```

feat(asus): add outOfStock label

---

docs/reference/filter.md
src/store/model/store.ts
src/store/model/wipoid.ts

Partly Fixes #1676 for wipoid stock not to be up to date at all. 
Updated Store contents for wipoid:
- Ryzen 5950 / 5900 added
- Added all currently listed 3090 cards not in config
- Added all currently listed 3080 cards not in config
- Added all currently listed 3070 cards not in config ( there were none in the config )
- Added all currently listed 3060ti cards not in config ( there were none in the config )
- update store.ts for additional card types currently missing
- Updated filter.md to fit missing card combinations to documentation 
-> Ryzen was tested successfully
-> 3090 was tested successfully
-> 3080 was tested successfully
-> 3070 was tested successfully
-> 3060ti was tested successfully

fix(wipoid): added 3090/3080/3070/3060ti/ryzen store items

---

src/store/model/computeruniverse.ts

Computeruniverse started listing most of the items "in Stock", basicly they added for 30 series cards another out of stock label.
added it to the out of stock list. 
done and verified, items show now properly out of stock.

fix(computeruniverse): false positives

---

src/store/model/acompc.ts

AcomPC had showing every card as in Stock for the last few days, after checking I found that the out Of Stock text was now under the same selector as the in Stock one, but with another text.
Updated this to the correct selector
Tested after changing out of stock is now working again as it should.

fix(acompc): false positives

---

src/store/model/newegg-ca.ts
src/store/model/newegg-sg.ts
src/store/model/newegg.ts

During test run to lockout for new cards on newegg for another fix i do currently prepare, i found that the newegg site ( US / CA / SG ) does give false positives in streetmerchant, showing in Stock items but are in reality out of stock.
Checking against the config file, there was no out of stock check in place and only an instock check, which seemed to hit nothing when cards are not in stock, but still got triggered. Since all 3 sites use the same layout I added ( and tested ) a proper out of stock check.
Testing has been done, Items out of stock show now proper out of stock and not the listed price / triggering false positives anymore.

fix(newegg): false positives (all stores)

---

src/store/model/newegg-ca.ts

Based upon #1741
Fittet all cards as before for newegg US / SG to local file requirements, removed the cart urls for this one, as they are missing completly and i do currently not have the actual links for them for the ca site. Furthermore, CA was somehow updated otherwise before and some cards from my US / SG update where already present, others still missing, but the old cards were all there.
this should sum up all updates for newegg for now
Local test was running fine and gave the awaited cards back.

chore(neweggca): add missing 3060ti, 3070, 3080, 3090 cards

---

src/store/model/newegg.ts

Fixes #1710
Added all currently not in config included 30 series cards from Newegg US.
Local test was running fine and gave the awaited cards back.

chore(newegg): add missing 3060ti, 3070, 3080, 3090 cards

---

src/store/model/newegg-sg.ts

Based upon #1741
Since all newegg store share the same inventory layout, but only differ in the url, added missing cards to SG location aswell ( fitted URLS to local shemata.
Local test was running fine and gave the awaited cards back.

chore(newegg-sg): add missing 3060ti, 3070, 3080, 3090 cards

---

docs/reference/filter.md
src/store/model/corsair-uk.ts
src/store/model/index.ts
src/store/model/store.ts

- New UK store variable: `corsair-uk`.
- Checks stock for SF600 Gold, SF600/SF750 Platinum.
- Checked against out of stock indicator to confirm it is working.
- Performed robust testing to ensure that it captures the stock correctly.

feat(store): corsair-uk

---

src/notification/discord.ts

This fix ensures that the `series` of a `link` is found in `notifyGroupSeries`. Before this fix, the first key in `notifyGroupSeries` was excluded. Typically, the first key is `3070`, so Discord notifications wouldn't include an `@mention` for the `3070` role. This fixes that bug.

fix(discord): ensure first group in list is notified

---

src/logger.ts
src/store/lookup.ts

This is intended to clean up the output so that there aren't a bunch of extraneous lines when using proxies.
Moves the `info` proxy calls to `debug`. I.E:
```
[10:32:52 PM] info :: ℹ [microcenter] Next proxy index: 2 / Count: 3
```
to:
```
[10:32:52 PM] debug :: ℹ [microcenter] Next proxy index: 2 / Count: 3
```
And then when proxies are being used, adds a proxy count before the store name.
Not using proxies:
```
[10:34:34 PM] info :: ✖ [microcenter] [evga (3080)] xc3 ultra :: OUT OF STOCK
[10:34:38 PM] warn :: ✖ [evga] [evga (3060ti)] xc gaming :: STATUS CODE ERROR 403
```
Using proxies:
```
[10:34:34 PM] info :: ✖ [1/3] [microcenter] [evga (3080)] xc3 ultra :: OUT OF STOCK
[10:34:38 PM] warn :: ✖ [1/3] [evga] [evga (3060ti)] xc gaming :: STATUS CODE ERROR 403
```
Use a proxy in …

feat: clean up proxy logging with n/N in each lookup

---

src/store/model/wipoid.ts

Fixes issue #1871
Is an error correction to commit be541713a8855f18b5102917751842e514796e00
During addition of the whole 30 series cards from the store, there happened a few copy / paste errors, leading to some false URLs.
Links are now corrected and should correspond to the correct product

fix(wipoid): corrected 3070 / 3080 links

---

docs/reference/notification.md
src/config.ts

Adds USCC to phone carrier options.
First PR, hopefully I'm doing this right.
Forked/modified/cloned locally.  Npm install, nothing broke.  Modified `dotenv` with `PHONE_CARRIER=uscc` and added phone number, npm run start with no errors.  Added `test:brand` and `test:series` via WebUI and got a txt message/email/discord alert shortly after.  There is a `sms.uscc.net` but it doesn't work for this.

feat(sms): add US Cellular

---

src/store/model/amazon-ca.ts

Fixes: #1884
During the testrun of #1851 the errors where not triggered. but i think somehow that the missing outofstockcheck in any store will cause problems at some point.
Testing done via VPN ( CA ) and directly to find additional issues, after adding out of stock check everything worked fine here.

fix(amazon-ca): out of stock check was missing

---

src/store/model/pccomponentes.ts

Added all the 3090, 3060ti, and rx6900xt series from pccomponentes.
Pccomponentes was only searching for 3070 and 3080 series. This adds other series currently available on the website.
Checked current stock and as there is none it shows out of stock. If necessary I will do further testing.

chore(pccomponentes): add 3090, 3060ti, rx6900xt

---

docs/reference/filter.md
src/store/model/index.ts
src/store/model/netonnet-no.ts

Added another norwegian store, netonnet.no - Since it exists in Sweden I let it have -no suffix. 
I've tested it with an in stock 3090 which checks out as in-stock and the obvious out of stock 3080's and 3060ti's.

feat(store): add netonnet-no

---

src/store/model/pcdiga.ts

Initial iteration of the pcdiga website support only added 3080 series.
This should improve and expand to support also the 3090, 3070 and  3060ti series.
Everything is out of stock for now, but tested with dotenv STORES=pcdiga

chore(pcdiga): add 3090, 3070, 3060ti

---

docs/reference/filter.md
src/store/model/mediamarkt.ts
src/store/model/notebooksbilliger.ts
src/store/model/saturn.ts
src/store/model/store.ts

Adds all RTX3060 I could find to notebooksbilliger and mediamarkt/saturn
For mediamarkt/saturn I could only find 2 product URLs for the time being.
I ran the bot with the added URL and it seems to work fine.
I verified all URLs to work.

chore(store): add 3060 for mediamarkt, saturn and notebooksbilliger

---

src/store/includes-labels.ts

Fixed parsing prices with thousands separator and European.
The problem was introduced by #2131 and described here #2151
Example: Newegg Canada's price for RTX 3070 "1,600.00" was interpreted as 1.6 
Tested manually and with a variety of stores around the world.

fix: parsing prices with thousands separator and European format

---

src/store/model/amd.ts

6900RX URL have changed, it is now [https://www.amd.com/en/direct-buy/5458374200/[locale]](https://www.amd.com/en/direct-buy/5458374200/us)
If you go to the former [URL](https://www.amd.com/en/direct-buy/5458372200/us). This will redirect you to the list of products, and wrongly state that the product is in stock, changing to the new url fixes that issue

chore(amd): update rx6900xt urls

---

src/store/model/amazon-uk.ts

This commit include a list of all the 3060 available by search on Amazon, used "include out of stock" option to collect them.

chore(amazon-uk): add 3060 cards

---

docs/reference/filter.md
src/store/model/ao.ts
src/store/model/bt.ts
src/store/model/index.ts

Adds support for PS5 on AO and BT. In both cases searching for PS5 takes users to a generic landing page, so I'm targeting the messages shown there.
Tested locally and ran them for some time in my own quest for a PS5.

feat(store): Add AO and BT (UK)

---

package-lock.json
package.json
src/store/model/index.ts

Applies to the `selected stores` information on startup.
Grayes out stores that have none of the selected brands/series/models as links. Additionally, if described event occurs, prints a line describing that some of the selected stores dont have what the user is looking for.
Prevents users (like me) from thinking the bot wouldn't work correctly because it isn't checking specific stores.
Tested across series, models, brands for 3070 and 3080 on alternate and amd. Successfully grayed out not matching stores.
None.

feat: color empty stores

---

src/store/model/amd-ca.ts
src/store/model/amd-de.ts
src/store/model/amd-it.ts
src/store/model/amd-uk.ts
src/store/model/amd.ts

AMD released a new version of the reference RX6800 XT on their shop yesterday. I have added the links to all relevant `amd` stores.
Created a new model for it in `store.ts` and made sure that specific link gets tested. Reports back stock correctly. For upstream, I left the model at `amd reference`, as it's just a black variant of the reference card.

chore(amd): add rx6800xt midnight black

---

docs/reference/filter.md
src/store/model/index.ts
src/store/model/mediamarkt-at.ts
src/store/model/wipoid.ts

Adds support for [mediamarkt.at](https://www.mediamarkt.at/)
- Included added store to the configuration, replaced a link from a graphics card with a product that exists and is available
- started the application and the graphic card model of the replaced link was shown in the logs

feat(store): add mediamarkt austria

---

src/notification/discord.ts

This commit adds promise resolution and objects to
be properly used within Promise.all function.
Before the `try {} catch {}` block would be exited
before the clients resolved their requests causing
uncaught errors from the notifications.
Also added object indexing to the notifyGroupSeries variable
to prevent typescript compile error.
Potentially Fixes:
- https://github.com/jef/streetmerchant/issues/2252
I failed to receive one of my alerts because of a uncaught error emanating from the discord notification webhook.
```
streetmerchant    | [6:52:25 PM] info :: 🚀🚨 [amazon] [{series} ({model})] ... :: IN STOCK 🚨🚀
streetmerchant    | https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=...&Quantity.1=1
streetmerchant    | [6:52:25 PM] info :: ✔ discord message sent <--- Here the app is …
```

fix(discord): properly wait for webhooks

---

src/store/model/amazon-es.ts

It was parsing 1800 as 1.8 resulting in unwanted notifications. Now it seems to work correctly.

fix(amazon-es): use euroFormat

---

docs/reference/captcha.md
mkdocs.yml
src/config.ts
src/messaging/discord.ts
src/messaging/slack.ts
test/functional/test-captcha.ts

Nav link was missing for the new captcha reference page, and added some important usage info that was only in the PR last time around (how to respond successfully to the bot). 
Also, updated captcha timeout and poll interval values to be seconds instead of milliseconds. This was done for the sake of consistency, as I noticed other duration config values were specified in seconds as well.

refactor(captcha): use seconds instead of ms

---

src/store/model/microcenter.ts

The current inStock label only looks for the words "in stock"; however, recent changes to Micro Center's website results in there sometimes being "0 NEW IN STOCK".
Refs #2407
Fixes #2407
Tested by setting `STORES=microcenter` then running.
Before the fix, it would show IN STOCK for everything, even when it was out of stock. With this branch, it shows OUT OF STOCK for everything (since that's the current state of the world as of testing).

fix(microcenter): add outOfStock label

---

src/store/model/alternate.ts

it often says "in stock" while also saying that it cannot be purchased instead of showing the cart button

fix(alternate): use button selector instead of text

---

src/store/fetch-links.ts
src/store/model/store.ts

I was trying to add a linksBuilder for some store, but the store loads the search results via ajax, so they were not in the response passed to linksBuilder.
Added two new options for linksBuilder:
- `waitUntil` - the same as in Store. allows to specify one of the `PuppeteerLifeCycleEvent` values.
- `waitForSelctor` - wait for the specified element to appear, using puppeteer's `page.waitForSelctor()`.

feat: add waitUntil and waitForSelctor to linksBuilder

---

package.json

Fixes #2232, #2369
Known issue starting in `open=^8.0.3`, details [here](https://github.com/sindresorhus/open/pull/238). Pinning to 8.0.2 for now will resolve this while the linked PR is approved.
- open `cmd`, navigate to sm directory
- run `npm i` with updated `package.json`
- ensure `OPEN_BROWSER` is not `false`
- run `npm run test:notification`, verify browser window opens while `cmd` window also remains open
- (can also run against test item and verify `cmd` continues processing after opening browser when using `npm run start`)

fix(lookup): prevent terminal from being hidden

---

src/store/model/otto.ts

fixes false positives for the series x (screenshot shows the series s page after redirect)
tested with docker local and the alert for series s still works. could not test series x because the page is currently hidden.

chore(otto): add labels for xbox series x & s

---

src/store/lookup.ts

Netonnet-no gives 403 even with many rotating proxies. I found out this is because a cookie. So the fix is to remove cookies before/after checking a new product. After getting a 403 it would work again (for a couple of products). This is because [cookies are cleared when an error occured](https://github.com/jef/streetmerchant/blob/main/src/store/lookup.ts#L276). 
Adding stores have been easy but I know I'm on deep water when editing `lookup.ts` however I do believe it should clear cookies when getting a new proxy regardless of the store. 
Tested 100+ product fetches on Netonnet-no, previously I would get 403 after 3-5 products.

fix: clear cookies when rotating proxies

---

src/store/model/bestbuy-ca.ts

Fixes #2641
Checking for inStock instead of the outOfStock element will make any error related to the page loading to be considered as "OutOfStock" instead of a false Positive.
- I've run the check for all the elements of BestBuy-ca for 30 minutes and there were no false positive.
- I've run the Positive check using test:series item and it appeared as In-Stock.

fix(bestbuy-ca): avoid false positive

---

src/messaging/discord.ts

Otherwise, a "TypeError [CLIENT_MISSING_INTENTS]" is thrown due to the upgraded to discord.js v13 in f14a1ca7. For more informations visist [https://discordjs.guide/additional-info/changes-in-v13.html#intents](https://discordjs.guide/additional-info/changes-in-v13.html#intents) 
```
error :: ✖ couldn't send discord DM Valid intents must be provided for the Client. {
"stack": "TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
at Client._validateOptions (/app/node_modules/discord.js/src/client/Client.js:544:13)
at new Client (/app/node_modules/discord.js/src/client/Client.js:73:10)
at getDiscordClientAsync (/app/build/src/messaging/discord.js:178:26)
at sendDMAsync (/app/build/src/messaging/discord.js:86:28)
at Object.sendDMAndGetResponseAsync …
```

fix(discord): add Discord.ClientOptions

---

docs/reference/filter.md
src/store/model/gamestop-ca.ts
src/store/model/index.ts
src/store/model/xbox.ts

EBGames has been renamed to Gamestop in Canada. I've removed `ebgames` and created `gamestop-ca` store. Also updated the store filter from the Docs.
- Added `gamestop-ca` store in `dotenv` and tested with `sonyps5c`, `sonyps5de`.
- Tested positive result using `test:series`.

chore(store): EBGames renamed to Gamestop (in Canada)

---

docs/reference/filter.md
src/store/model/hardware-planet.ts
src/store/model/index.ts
src/store/model/ldlc-italy.ts
src/store/model/ollo.ts

Update broken hardware-planet
update ollo test

feat: add ldlc-italy and fixes ollo/hardware-planet

---

src/store/model/amazon.ts

Amazon US was not pulling prices.
Manually tested items are being filtered on Amazon by price

fix: amazon prices

---

src/store/model/newegg.ts

Fixed mislableld link in store model, it was labeled as a 5090 when it is a link to 5080.
I got a false positive where it alerted to a newegg 5080 astral when i only wanted 5090
Ran against 5090 targeted scanning, worked as expected.

fix:  Corrected label for newegg asus astral 5080

---

src/store/model/newegg.ts

Currently, the MAX_PRICE_* feature doesn't work with Newegg, because it's using the wrong selector. This change updates the selector so that the product price is correctly selected. I've also changed the `outOfStock` selector to `.product-buy` because `.product-inventory` does not exist on the product page.
- I tested the Out of Stock functionality and works as it should.
- To test the max price feature, I manually changed a product link in the Newegg store that was in stock and set a MAX_PRICE. I've verified the notification is ignored if the product is over the max set.

fix: update selector for newegg product price
